config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'gyms#index'
  resources :teams, only: [:new, :create, :destroy]
  resources :gyms, only: [:index, :show] do
  collection do
    get 'search'
  end
  end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :gym
end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :favorites

  def self.search(search)
    if search != ''
      Gym.where('name LIKE(?)', "%#{search}%").or(Gym.where('address LIKE(?)', "%#{search}%"))
    else
      Gym.all
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :plan_id, scope: :user_id
  with_options presence: true do
    validates :user_id
    validates :customer_id
    validates :active_until
    validates :stripe_subscription_id
    validates :plan_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :phone, presence: true

  has_many :favorites, dependent: :destroy
  has_one :team

  def unsubscribe
    team = Team.find_by(user_id: id)
    team.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_gym
  def create
    @favorite = Favorite.new(user_id: current_user.id, gym_id: params[:gym_id])
    @favorite.save
    redirect_to root_path
  end

  def destroy
    @favorite = current_user.favorites.find_by(gym_id: @gym.id)
    @favorite.destroy
    redirect_to root_path
  end

  private

  def set_gym
    @gym = Gym.find(params[:gym_id])
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  def index
    @gyms = Gym.all
  end

  def show
    @gym = Gym.find(params[:id])
    gon.lat = @gym.lat.to_f
    gon.lng = @gym.lng.to_f
  end

  def search
    @gyms = Gym.search(params[:keyword])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
    @user = current_user
    @team = Team.find_by(user_id: @user.id)
  end

  def create
    @team = Team.new(user_id: current_user.id)
    customer = Stripe::Customer.create({
                                         source: params[:stripeToken]
                                       })
    subscription = Stripe::Subscription.create({
                                                 customer: customer.id,
                                                 plan: 'price_1LNWJtCUmfQ7g7y2yJZWEbuo'
                                               })
    @team.plan_id = 'price_1LNWJtCUmfQ7g7y2yJZWEbuo'
    @team.customer_id = customer.id
    @team.stripe_subscription_id = subscription.id
    @team.active_until = Time.zone.at(subscription.current_period_end)
    if @team.save
      flash[:success] = '成功しました'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @team = Team.find_by(user_id: current_user.id)
    deleting_stripe_subscription = Stripe::Subscription.retrieve(@team.stripe_subscription_id)
    if current_user.unsubscribe
      deleting_stripe_subscription.delete
      flash[:notice] = '解約に成功しました'
      redirect_to root_url
    else
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @gyms = @user.gyms

    favorites = Favorite.where(user_id: current_user.id).pluck(:gym_id)
    @favorite_list = Gym.find(favorites)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/index.html.erb
<%= render partial: "layouts/header" %>

<%= render partial: "layouts/search" %>



        <!-- 表 -->
        <div class="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">店舗名</th>
                        <th scope="col">電話番号</th>
                        <th scope="col">所在地</th>
                        <th scope="col" colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <% @gyms.each do |gym| %>
                        <td><%= gym.name %></td>
                        <td><%= gym.phone %></td>
                        <td><%= gym.address %></td>
                        <td>
                            <%= link_to '詳細', gym_path(gym.id),class:"btn btn-secondary btn-sm" %>
                            <i class="fa fa-アイコン名" aria-hidden="true"></i>
                        </td>
                    </tr>                                
                      <% end %>
                </tbody>
            </table>
            <br/>
            <div class="row">
                <div class="mx-auto">
                    <div class="flex-column justify-content-center">
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                <a class="btn btn-outline-primary" href="#p-=1" role="button">«</a>
                                <a class="btn btn-outline-primary" href="#p=1" role="button">1</a>
                                <a class="btn btn-outline-primary active" href="#p=2" role="button">2</a>
                                <a class="btn btn-outline-primary" href="#p=3" role="button">3</a>
                                <a class="btn btn-outline-primary" href="#p=4" role="button">4</a>
                                <a class="btn btn-outline-primary" href="#p=5" role="button">5</a>
                                <a class="btn btn-outline-primary" href="#p=6" role="button">6</a>
                                <a class="btn btn-outline-primary disabled" href="#" role="button">...</a>
                                <a class="btn btn-outline-primary" href="#p+=1" role="button">»</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- モーダルウィンドウ -->
        <div class="modal fade" id="sample1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">データの削除</h5>
                    </div>
                    <div class="modal-body">
                        <p>削除してよろしいですか？</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                        <form action="./test1.html" method="POST" class="form-inline">
                            <button type="submit" class="btn btn-danger">削除</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="my-4 text-center">
            <p><a href="#" onClick="window.close();" class="btn btn-danger" role="button"><i class="fas fa-window-close fa-fw" aria-hidden="true"></i>閉じる</a></p>
        </div>
        
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

app/views/gyms/_gym.html.erb
                    <tr>
                        <td><%= gym.name %></td>
                        <td><%= gym.phone %></td>
                        <td><%= gym.address %></td>
                        <td>
                            <%= link_to '詳細', gym_path(gym.id),class:"btn btn-secondary btn-sm" %>
                            <i class="fa fa-アイコン名" aria-hidden="true"></i>
                        </td>
                    </tr>                               

app/views/gyms/index.html.erb
<%= render partial: "layouts/header", locals: { team: @team } %>

<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="7000">
      <img src="assets/image1.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>あなたの得意を活かしませんか？</h5>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="7000">
      <img src="assets/image2.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>近隣のフィットネスクラブが探せます</h5>
      </div>
    </div>
    <div class="carousel-item">
      <img src="assets/image3.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>さあ、すぐにはじめましょう！</h5>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


<div class="input-group mb-3">
  <%= form_with(url: search_gyms_path, local: true, method: :get, class: "form-control") do |form| %>
    <%= form.text_field :keyword, placeholder: "店舗名・所在地で検索する", class: "form-control" %>
    <%= form.submit "検索", class:"btn btn-outline-info" %>
  <% end %>
</div>

app/views/gyms/search.html.erb
<%= render partial: "layouts/header" %>

<div class="input-group mb-3">
  <%= form_with(url: search_gyms_path, local: true, method: :get, class: "form-control") do |form| %>
    <%= form.text_field :keyword, placeholder: "店舗名・所在地で検索する", class: "form-control" %>
    <%= form.submit "検索", class:"btn btn-outline-secondary" %>
  <% end %>
</div>
<% if @gyms.present? %>
<div class="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">店舗名</th>
                        <th scope="col">電話番号</th>
                        <th scope="col">所在地</th>
                        <th scope="col" colspan="2"></th>
                    </tr>
                </thead>
  <% @gyms.each do |gym| %>
    <%= render partial: "gym", locals: { gym: gym } %>
  <% end %>
  <% else %>
    <% end %>
            <br/>

app/views/gyms/show.html.erb
<%= render partial: "layouts/header" %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=  'AIzaSyDqMqBKtBHk44SypsJ1BeTugqz2spBVhgQ' %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>



<h2>map</h2>
<div id='map'></div>

<style>
#map {
  height: 300px;
  width: 285px;
}
</style>

<script>
let map

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: gon.lat, lng: gon.lng },
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: gon.lat, lng: gon.lng },
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqMqBKtBHk44SypsJ1BeTugqz2spBVhgQ&callback=initMap" async defer></script>

<div class="card" style="width: 18rem;">
  <img src="<%= "#{@gym.Image}" %>" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">店舗情報</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @gym.name %></li>
    <li class="list-group-item"><a href="tel:@gym.phone"><%= @gym.phone %></a></li>
    <li class="list-group-item"><%= @gym.address %></li>
  </ul>
  <div class="card-body">
    <%= link_to '店舗URL', @gym.url, target: :_blanck, rel: "noopener noreferrer", class:"card-link" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Headers · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/headers/">
    </head>

    <body>
        <!-- メニュー -->
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
    <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
  </symbol>
</svg>

<main>
  <h1 class="visually-hidden">Headers examples</h1>

  <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/gyms" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
         <span class="fs-4">Gym searcher</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item">
        <%= link_to current_user.name, edit_user_registration_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to "有償版へグレードアップ", new_team_path,  class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      </ul>
    </header>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>